[env:esp32-wrover]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -I include
    -D CORE_DEBUG_LEVEL=3
    -D MINAS_FW_VERSION=\"wrover-driver-collection-v1\"
lib_deps =
    https://github.com/rodneybakiskan/ps5-esp32.git
    madhephaestus/ESP32Servo@^3.0.6
