; PlatformIO Project Configuration File for MinasDT
; ----------------------------------------------------------------------------
; Project: MinasDT (Data Transmitter)
; Author: Eyal Braun & Manus AI
; Description: RC Car Controller with ESP-NOW Telemetry.
; ----------------------------------------------------------------------------

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor Settings
monitor_speed = 115200

; Build Flags
build_flags = 
    -I include
    -D CORE_DEBUG_LEVEL=3

; Library Dependencies
lib_deps =
    madhephaestus/ESP32Servo @ ^1.1.0
    ; ps5-controller library is required (manually install or add URL)
    https://github.com/Artayeb/ps5-controller.git
