; MinasDT - Data Transmitter
; חשוב: ספריית PS5 זו משתמשת ב-Bluetooth Classic.
; לכן יש להשתמש ב-ESP32 קלאסי, לא ב-ESP32-S3.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200

lib_ldf_mode = deep+

build_flags =
    -I include
    -I .pio/libdeps/esp32dev/ps5Controller/src
    -D CORE_DEBUG_LEVEL=3
    -D MINAS_FW_VERSION=\"collection-v1\"

lib_deps =
    madhephaestus/ESP32Servo @ ^1.2.1
    https://github.com/rodneybakiskan/ps5-esp32.git
