; PlatformIO Project Configuration File for MinasDT
; ----------------------------------------------------------------------------
; Project: MinasDT (Data Transmitter)
; Author: Eyal Braun & Manus AI
; Description: RC Car Controller with ESP-NOW Telemetry & MRP Security.
; ----------------------------------------------------------------------------

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor Settings
monitor_speed = 115200

; אומר ל-PlatformIO לחפש ספריות גם בתיקייה אחת מעל (שם נמצאת shared)
lib_extra_dirs = ../

; Build Flags
build_flags = 
    -I include
    -D CORE_DEBUG_LEVEL=3

; Library Dependencies
lib_deps =
    madhephaestus/ESP32Servo @ ^1.1.0
    https://github.com/Artayeb/ps5-controller.git
