[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.partitions = huge_app.csv
lib_ldf_mode = deep+
build_flags =
    -I include
    -I .
    -D MINAS_FW_VERSION=\"dr-authorized-actuator-v2\"
lib_deps =
    madhephaestus/ESP32Servo @ ^1.2.1
